from enum import Enum


class ErrorKind(Enum):
    ERROR_MISSING_MAIN = 1
    ERROR_UNDEFINED_VARIABLE = 2
    ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION = 3
    ERROR_NOT_A_FUNCTION = 4
    ERROR_NOT_A_TUPLE = 5
    ERROR_NOT_A_RECORD = 6
    ERROR_NOT_A_LIST = 7
    ERROR_UNEXPECTED_LAMBDA = 8
    ERROR_UNEXPECTED_TYPE_FOR_PARAMETER = 9
    ERROR_UNEXPECTED_TUPLE = 10
    ERROR_UNEXPECTED_RECORD = 11
    ERROR_UNEXPECTED_VARIANT = 12
    ERROR_UNEXPECTED_LIST = 13
    ERROR_UNEXPECTED_INJECTION = 14
    ERROR_MISSING_RECORD_FIELDS = 15
    ERROR_UNEXPECTED_RECORD_FIELDS = 16
    ERROR_UNEXPECTED_FIELD_ACCESS = 17
    ERROR_UNEXPECTED_VARIANT_LABEL = 18
    ERROR_TUPLE_INDEX_OUT_OF_BOUNDS = 19
    ERROR_UNEXPECTED_TUPLE_LENGTH = 20
    ERROR_AMBIGUOUS_SUM_TYPE = 21
    ERROR_AMBIGUOUS_VARIANT_TYPE = 22
    ERROR_AMBIGUOUS_LIST = 23
    ERROR_ILLEGAL_EMPTY_MATCHING = 24
    ERROR_NONEXHAUSTIVE_MATCH_PATTERNS = 25
    ERROR_UNEXPECTED_PATTERN_FOR_TYPE = 26
    ERROR_DUPLICATE_RECORD_FIELDS = 27
    ERROR_DUPLICATE_RECORD_TYPE_FIELDS = 28
    ERROR_DUPLICATE_VARIANT_TYPE_FIELDS = 29
    ERROR_INCORRECT_ARITY_OF_MAIN = 30
    ERROR_DUPLICATE_RECORD_PATTERN_FIELDS = 31
    ERROR_EXCEPTION_TYPE_NOT_DECLARED = 32
    ERROR_AMBIGUOUS_THROW_TYPE = 33
    ERROR_AMBIGUOUS_REFERENCE_TYPE = 34
    ERROR_AMBIGUOUS_PANIC_TYPE = 35
    ERROR_NOT_A_REFERENCE = 36
    ERROR_UNEXPECTED_MEMORY_ADDRESS = 37
    ERROR_UNEXPECTED_SUBTYPE = 38
    ERROR_UNEXPECTED_REFERENCE = 39
